import React, { useState } from 'react';
import { ActivityIndicator, Alert, Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import * as ImagePicker from 'expo-image-picker';
import { ImageManipulator, SaveFormat } from 'expo-image-manipulator';
import { User } from '../../services/api';
export default function ProfileScreen({ user, photo, onPhoto, savedCount, reminderCount, logout }: { user: User; photo: string | null; onPhoto: (photo: string | null) => void; savedCount: number; reminderCount: number; logout: () => void }) {
 const [busy, setBusy] = useState(false);
 async function pick() { if (busy) return; setBusy(true); try {
  const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [1, 1], quality: .8 });
  if (!result.canceled && result.assets[0]) { const context = ImageManipulator.manipulate(result.assets[0].uri); context.resize({ width: 512 }); const image = await context.renderAsync(); const output = await image.saveAsync({ compress: .75, format: SaveFormat.JPEG, base64: true }); if (output.base64) onPhoto('data:image/jpeg;base64,' + output.base64); }
 } catch { Alert.alert('Could not change photo', 'Please choose another image and try again.'); } finally { setBusy(false); } }
 return <ScrollView showsVerticalScrollIndicator={false} showsHorizontalScrollIndicator={false} contentContainerStyle={s.content}><Text style={s.title}>Your Profile</Text><View style={s.identity}><Pressable accessibilityLabel="Edit profile picture" accessibilityRole="button" disabled={busy} onPress={pick} style={s.avatar}>{photo ? <Image source={{ uri: photo }} style={s.photo}/> : <Text style={s.initial}>{user.fullName.slice(0, 1).toUpperCase()}</Text>}<View style={s.camera}>{busy ? <ActivityIndicator size="small" color="#fff"/> : <Ionicons name="camera" size={18} color="#fff"/>}</View></Pressable><Pressable onPress={pick} disabled={busy} style={s.edit}><Text style={s.editText}>{busy ? 'Updating photo…' : 'Change Profile Picture'}</Text></Pressable>{photo && <Pressable onPress={() => onPhoto(null)} style={s.remove}><Text style={s.secondary}>Remove photo</Text></Pressable>}<Text style={s.name}>{user.fullName}</Text><Text style={s.role}>Event Seeker</Text></View><View style={s.details}><Text style={s.label}>FULL NAME</Text><Text style={s.value}>{user.fullName}</Text><View style={s.divider}/><Text style={s.label}>EMAIL ADDRESS</Text><Text selectable style={s.value}>{user.email}</Text></View><View style={s.stats}><View style={s.stat}><Text style={s.number}>{savedCount}</Text><Text style={s.secondary}>Saved events</Text></View><View style={s.stat}><Text style={s.number}>{reminderCount}</Text><Text style={s.secondary}>Reminders</Text></View></View><Text style={s.note}>Your photo, saved events, and demo reminders are stored on this device for your account.</Text><Pressable onPress={logout} style={s.logout}><Ionicons name="log-out-outline" size={20} color="#0B7A3E"/><Text style={s.editText}>Log Out</Text></Pressable></ScrollView>;
}
const s = StyleSheet.create({ content: { padding: 22, width: '100%', maxWidth: 560, alignSelf: 'center' }, title: { fontSize: 26, fontWeight: '800', color: '#182230' }, identity: { alignItems: 'center', paddingVertical: 30 }, avatar: { width: 110, height: 110, borderRadius: 55, backgroundColor: '#DDEEE3', alignItems: 'center', justifyContent: 'center' }, photo: { width: 110, height: 110, borderRadius: 55 }, initial: { color: '#0B7A3E', fontSize: 44, fontWeight: '800' }, camera: { position: 'absolute', bottom: 0, right: 0, width: 34, height: 34, borderRadius: 17, backgroundColor: '#0B7A3E', borderWidth: 2, borderColor: '#fff', alignItems: 'center', justifyContent: 'center' }, edit: { minHeight: 44, justifyContent: 'center', marginTop: 10 }, editText: { color: '#0B7A3E', fontWeight: '700', fontSize: 14 }, remove: { minHeight: 36, justifyContent: 'center' }, name: { fontSize: 23, fontWeight: '800', color: '#182230', marginTop: 12, textAlign: 'center' }, role: { color: '#0B7A3E', backgroundColor: '#E7F4EC', borderRadius: 8, padding: 8, marginTop: 12 }, details: { backgroundColor: '#fff', borderRadius: 14, borderWidth: 1, borderColor: '#E4E7EC', padding: 18 }, label: { fontSize: 10, fontWeight: '700', color: '#667085', letterSpacing: .8 }, value: { color: '#344054', fontSize: 15, marginTop: 9 }, divider: { borderTopWidth: 1, borderTopColor: '#EAECF0', marginVertical: 18 }, stats: { flexDirection: 'row', paddingVertical: 25 }, stat: { flex: 1, alignItems: 'center', gap: 7 }, number: { color: '#0B7A3E', fontSize: 25, fontWeight: '800' }, secondary: { color: '#667085', fontSize: 12 }, note: { color: '#667085', fontSize: 11, lineHeight: 18, textAlign: 'center' }, logout: { flexDirection: 'row', gap: 10, justifyContent: 'center', padding: 16, borderWidth: 1, borderColor: '#C8DACE', borderRadius: 12, marginTop: 25 } });
