import React, { useMemo, useState } from 'react';
import { Alert, Image, Linking, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { WebView } from 'react-native-webview';
import { SeekerEvent } from './data/events';
export default function EventLocationScreen({ event, onBack }: { event: SeekerEvent; onBack: () => void }) {
 const query = encodeURIComponent([event.venue, event.address, event.city, 'Sri Lanka'].join(', '));
 const open = (directions: boolean) => Linking.openURL(directions ? 'https://www.google.com/maps/dir/?api=1&destination=' + query : 'https://www.google.com/maps/search/?api=1&query=' + query).catch(() => Alert.alert('Unable to open Maps', 'Please try again.'));
 return <View style={s.root}><View style={s.header}><Pressable accessibilityLabel="Back to event" onPress={onBack} style={s.back}><Ionicons name="chevron-back" size={26} color="#182230"/></Pressable><Text style={s.title}>Event Location</Text></View><View style={[s.map, { alignItems: 'center', justifyContent: 'center' }]}><Ionicons name="location-outline" size={48} color="#0B7A3E"/><Text style={s.eventTitle}>{event.venue}</Text><Text style={s.city}>{event.address}, {event.city}</Text></View><View style={s.sheet}><View style={s.handle}/><View style={s.event}><Image source={event.image} style={s.thumbnail}/><Text style={s.eventTitle}>{event.title}</Text></View><Pressable style={s.open} onPress={() => open(false)}><Text style={s.openText}>Open in Maps</Text></Pressable><Pressable style={s.directions} onPress={() => open(true)}><Text style={s.directionText}>Get Directions</Text></Pressable></View></View>;
}
const s = StyleSheet.create({ root: { flex: 1, backgroundColor: '#fff' }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 58, paddingHorizontal: 12 }, back: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, title: { fontSize: 18, fontWeight: '700', color: '#182230' }, map: { flex: 1, minHeight: 160, backgroundColor: '#E5EEDC' }, sheet: { borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: '#fff', marginTop: -18, paddingHorizontal: 18, paddingBottom: 12 }, handle: { width: 40, height: 4, borderRadius: 2, backgroundColor: '#CED7E3', alignSelf: 'center', marginVertical: 16 }, event: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 19 }, thumbnail: { width: 55, height: 55, borderRadius: 12 }, eventTitle: { color: '#182230', fontWeight: '700', fontSize: 16 }, city: { color: '#667085', fontSize: 12, marginTop: 6 }, price: { color: '#087A44', backgroundColor: '#ECFDF3', borderWidth: 1, borderColor: '#A6E6C3', borderRadius: 12, paddingHorizontal: 10, paddingVertical: 4, fontSize: 12 }, open: { flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#86C9A5', borderRadius: 12, minHeight: 48 }, openText: { color: '#0B7A3E', fontSize: 15, fontWeight: '700' }, directions: { flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', borderRadius: 12, minHeight: 50, backgroundColor: '#0B7A3E', marginTop: 10 }, directionText: { color: '#fff', fontSize: 15, fontWeight: '700' }, note: { color: '#667085', fontSize: 10, lineHeight: 16, textAlign: 'center', marginTop: 8 } });
