import React, { useMemo, useState } from 'react';
import { Alert, Image, Linking, Platform, Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { WebView } from 'react-native-webview';
import { DemoEvent } from './data/demoEvents';
const locations: Record<string, [number, number]> = { perahera: [7.2936, 80.6413], temple: [7.2936, 80.6413], food: [6.922, 79.8445], music: [6.026, 80.217], jazz: [6.9271, 79.8612], 'beach-dj': [5.9447, 80.4586], 'local-band': [7.209, 79.838] };
export function mapDocument(destination: [number, number], directions: boolean) {
 return `<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1"><link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"><style>html,body,#map{height:100%;margin:0;font-family:system-ui;background:#e5eedc}#status{position:absolute;top:12px;left:12px;right:12px;z-index:900;background:white;padding:10px 12px;border-radius:10px;font-size:12px;color:#344054;box-shadow:0 2px 8px #0002}#center{position:absolute;right:16px;bottom:32px;z-index:900;border:0;border-radius:50%;width:46px;height:46px;background:white;font-size:24px;box-shadow:0 3px 10px #0002}.pin{background:#e52259;border:3px solid white;border-radius:50%;width:20px!important;height:20px!important;box-shadow:0 2px 8px #0004}#steps{position:absolute;bottom:30px;left:12px;right:76px;z-index:900;background:white;border-radius:10px;max-height:95px;overflow:auto;font-size:12px;padding:10px;display:none;scrollbar-width:none}#steps::-webkit-scrollbar{display:none}</style></head><body><div id="map"></div><div id="status">Loading event map…</div><button id="center" aria-label="Center on event">◎</button><div id="steps"></div><script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js" onerror="document.getElementById('status').textContent='Map could not load. Check your connection and retry.'"></script><script>
const destination=${JSON.stringify(destination)}, directions=${directions};
const status=document.getElementById('status');
if(window.L){const map=L.map('map',{zoomControl:false}).setView(destination,15);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>'}).addTo(map).on('tileerror',()=>{status.textContent='Some map tiles could not load. Check your connection.'});L.marker(destination,{icon:L.divIcon({className:'pin',iconSize:[20,20],iconAnchor:[10,10]})}).addTo(map).bindTooltip('Event location');document.getElementById('center').onclick=()=>map.setView(destination,15);status.textContent=directions?'Loading driving directions…':'Demo event location • Pinch to zoom';
let line,startMarker;let requestId=0;
async function route(start){const current=++requestId;if(line){map.removeLayer(line);line=null;}if(startMarker){map.removeLayer(startMarker);startMarker=null;}document.getElementById('steps').style.display='none';status.textContent='Loading driving route…';try{const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),15000);let response;try{response=await fetch('https://router.project-osrm.org/route/v1/driving/'+start[1]+','+start[0]+';'+destination[1]+','+destination[0]+'?overview=full&geometries=geojson&steps=true',{signal:controller.signal});}finally{clearTimeout(timer);}const data=await response.json();if(current!==requestId)return;if(data.code!=='Ok'||!data.routes[0])throw Error();const result=data.routes[0];if(line)map.removeLayer(line);if(startMarker)map.removeLayer(startMarker);line=L.geoJSON(result.geometry,{style:{color:'#087a44',weight:6}}).addTo(map);startMarker=L.circleMarker(start,{radius:7,color:'white',weight:3,fillColor:'#3187fa',fillOpacity:1}).addTo(map).bindTooltip('Starting point');map.fitBounds(line.getBounds(),{padding:[40,60]});status.textContent=(result.distance/1000).toFixed(1)+' km • '+Math.max(1,Math.round(result.duration/60))+' min drive • Tap map to change start';const steps=document.getElementById('steps');steps.replaceChildren();result.legs[0].steps.forEach(step=>{const item=document.createElement('div');item.textContent=(step.maneuver.type==='arrive'?'Arrive at event':step.maneuver.type.replaceAll('_',' ')+(step.maneuver.modifier?' '+step.maneuver.modifier:'')+(step.name?' on '+step.name:''))+' · '+Math.round(step.distance)+' m';item.style.padding='4px 0';steps.appendChild(item);});steps.style.display='block';}catch{if(current===requestId){status.textContent='Route unavailable. Tap a different starting point to retry.';}}}
if(directions){route([destination[0]-0.012,destination[1]-0.008]);map.on('click',e=>route([e.latlng.lat,e.latlng.lng]));}}
</script></body></html>`;
}
export default function EventLocationScreen({ event, onBack }: { event: DemoEvent; onBack: () => void }) {
 const [directions, setDirections] = useState(false), [retry, setRetry] = useState(0);
 const destination = locations[event.id] ?? [7.2936, 80.6413];
 const html = useMemo(() => mapDocument(destination, directions), [event.id, directions, retry]);
 return <View style={s.root}><View style={s.header}><Pressable accessibilityLabel="Back to event" onPress={onBack} style={s.back}><Ionicons name="chevron-back" size={26} color="#182230"/></Pressable><Text style={s.title}>Event Location</Text><Pressable accessibilityLabel="Reload map" onPress={() => setRetry(v => v + 1)} style={s.back}><Ionicons name="refresh-outline" size={20} color="#667085"/></Pressable></View><View style={s.map}>{Platform.OS === 'web' ? React.createElement('iframe', { title: 'Event location map', srcDoc: html, sandbox: 'allow-scripts allow-same-origin', style: { width: '100%', height: '100%', border: 0 } }) : <WebView key={retry} source={{ html, baseUrl: 'https://lankafest.local/' }} originWhitelist={['*']} javaScriptEnabled showsVerticalScrollIndicator={false} showsHorizontalScrollIndicator={false} onShouldStartLoadWithRequest={request => request.url === 'about:blank' || request.url.startsWith('https://lankafest.local/')} onError={() => Alert.alert('Map unavailable', 'Check your connection and use the reload button.')} style={{ flex: 1 }}/>}</View><View style={s.sheet}><View style={s.handle}/><View style={s.event}><Image source={event.image} style={s.thumbnail}/><View style={{ flex: 1 }}><Text style={s.eventTitle}>{event.title}</Text><Text style={s.city}><Ionicons name="location-outline" size={13}/> {event.city}, Sri Lanka</Text></View><Text style={s.price}>{event.price ? 'LKR ' + event.price.toLocaleString() : 'Free'}</Text></View><Pressable style={s.open} onPress={() => Linking.openURL('https://www.google.com/maps/search/?api=1&query=' + destination.join(',')).catch(() => Alert.alert('Unable to open Maps', 'Please try again.'))}><Ionicons name="location" size={19} color="#0B7A3E"/><Text style={s.openText}>Open in Maps</Text></Pressable><Pressable style={s.directions} onPress={() => setDirections(v => !v)}><Ionicons name="navigate" size={19} color="#fff"/><Text style={s.directionText}>{directions ? 'Hide Directions' : 'Get Directions'}</Text></Pressable><Text style={s.note}>{directions ? 'Demo starting point. Tap the map to choose your start.' : 'Demo venue pin. Map and driving routes require internet.'}</Text></View></View>;
}
const s = StyleSheet.create({ root: { flex: 1, backgroundColor: '#fff' }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', minHeight: 58, paddingHorizontal: 12 }, back: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, title: { fontSize: 18, fontWeight: '700', color: '#182230' }, map: { flex: 1, minHeight: 160, backgroundColor: '#E5EEDC' }, sheet: { borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: '#fff', marginTop: -18, paddingHorizontal: 18, paddingBottom: 12 }, handle: { width: 40, height: 4, borderRadius: 2, backgroundColor: '#CED7E3', alignSelf: 'center', marginVertical: 16 }, event: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 19 }, thumbnail: { width: 55, height: 55, borderRadius: 12 }, eventTitle: { color: '#182230', fontWeight: '700', fontSize: 16 }, city: { color: '#667085', fontSize: 12, marginTop: 6 }, price: { color: '#087A44', backgroundColor: '#ECFDF3', borderWidth: 1, borderColor: '#A6E6C3', borderRadius: 12, paddingHorizontal: 10, paddingVertical: 4, fontSize: 12 }, open: { flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#86C9A5', borderRadius: 12, minHeight: 48 }, openText: { color: '#0B7A3E', fontSize: 15, fontWeight: '700' }, directions: { flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', borderRadius: 12, minHeight: 50, backgroundColor: '#0B7A3E', marginTop: 10 }, directionText: { color: '#fff', fontSize: 15, fontWeight: '700' }, note: { color: '#667085', fontSize: 10, lineHeight: 16, textAlign: 'center', marginTop: 8 } });
