import React, { useEffect, useState } from 'react';
import { Alert, BackHandler, Image, Pressable, ScrollView, Share, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import EventLocationScreen from './EventLocationScreen';
import { DemoEvent } from './data/demoEvents';
export default function EventDetailsScreen({ event, saved, reminder, onSave, onReminder, onBack }: { event: DemoEvent; saved: boolean; reminder: boolean; onSave: () => void; onReminder: () => void; onBack: () => void }) {
 const [locationVisible, setLocationVisible] = useState(false);
 useEffect(() => { const listener = BackHandler.addEventListener('hardwareBackPress', () => { if (locationVisible) setLocationVisible(false); else onBack(); return true; }); return () => listener.remove(); }, [onBack, locationVisible]);
 const row = (icon: React.ComponentProps<typeof Ionicons>['name'], label: string, free = false) => <View style={s.row}><Ionicons name={icon} size={19} color="#8993A2"/><Text style={[s.value, free && { color: '#0B7A3E', fontWeight: '700' }]}>{label}</Text></View>;
 if (locationVisible) return <EventLocationScreen event={event} onBack={() => setLocationVisible(false)}/>;
 return <View style={s.root}><ScrollView showsVerticalScrollIndicator={false} showsHorizontalScrollIndicator={false} contentContainerStyle={s.content}>
  <View style={s.cover}><Image source={event.image} style={s.image}/><View style={s.tools}><Pressable accessibilityLabel="Back to events" onPress={onBack} style={s.circle}><Ionicons name="chevron-back" size={24} color="#25312A"/></Pressable><View style={s.rightTools}><Pressable accessibilityLabel={saved ? 'Unsave event' : 'Save event'} accessibilityState={{ selected: saved }} onPress={onSave} style={s.circle}><Ionicons name={saved ? 'heart' : 'heart-outline'} size={23} color="#E44755"/></Pressable><Pressable accessibilityLabel="Share event" style={s.circle} onPress={() => { Share.share({ message: event.title + '\n' + event.city + ', Sri Lanka • ' + event.date + '\nDemo event on LankaFest Connect' }).catch(() => Alert.alert('Unable to share', 'Please try again.')); }}><Ionicons name="share-social-outline" size={22} color="#25312A"/></Pressable></View></View><View style={s.badge}><Ionicons name="checkmark-circle" size={13} color="#087A49"/><Text style={s.badgeText}>{event.badge === 'VERIFIED EVENT' ? 'Verified Event' : event.badge}</Text></View></View>
  <View style={s.body}><Text style={s.title}>{event.title}</Text><Text style={s.subtitle}>{event.id === 'perahera' ? 'Sacred processions, traditional dancers and rich cultural heritage.' : event.venue}</Text>
   <View style={s.metadata}>{row('calendar-outline', event.date)}{row('time-outline', '6:00 PM – 11:00 PM')}{row('location-outline', event.city + ', Sri Lanka')}<Pressable style={s.map} onPress={() => setLocationVisible(true)}><Text style={s.mapText}>View on Map</Text></Pressable>{row('ticket-outline', event.price ? 'LKR ' + event.price.toLocaleString() : 'Free', true)}{row('pricetag-outline', event.id === 'perahera' ? 'Cultural • Religious' : event.category)}</View>
   <Text style={s.description}>{event.description}</Text><Text style={s.note}>Demo schedule and verification. Reminders appear in your Notifications list on this device.</Text>
   {reminder && <View style={s.confirmation}><Ionicons name="checkmark-circle" size={18} color="#0B7A3E"/><Text style={s.confirmText}>Reminder added to Notifications.</Text></View>}
  </View>
 </ScrollView><View style={s.footer}><Pressable onPress={onSave} accessibilityState={{ selected: saved }} style={s.save}><Ionicons name={saved ? 'bookmark' : 'bookmark-outline'} size={20} color="#344054"/><Text style={s.saveText}>{saved ? 'Saved' : 'Save'}</Text></Pressable><Pressable onPress={onReminder} accessibilityLabel={reminder ? 'Remove reminder' : 'Set reminder'} style={s.reminder}><Ionicons name={reminder ? 'checkmark-circle-outline' : 'notifications-outline'} size={19} color="#fff"/><Text style={s.reminderText}>{reminder ? 'Remove Reminder' : 'Set Reminder'}</Text></Pressable></View></View>;
}
const s = StyleSheet.create({ root: { flex: 1, backgroundColor: '#fff' }, content: { width: '100%', maxWidth: 560, alignSelf: 'center', paddingBottom: 24 }, cover: { height: 285 }, image: { width: '100%', height: '100%' }, tools: { position: 'absolute', top: 12, left: 14, right: 14, flexDirection: 'row', justifyContent: 'space-between' }, rightTools: { flexDirection: 'row', gap: 10 }, circle: { width: 44, height: 44, borderRadius: 22, backgroundColor: '#FFFFFFE8', alignItems: 'center', justifyContent: 'center' }, badge: { position: 'absolute', bottom: 14, left: 14, flexDirection: 'row', alignItems: 'center', gap: 5, borderRadius: 15, paddingHorizontal: 10, paddingVertical: 5, backgroundColor: '#E5F5ED' }, badgeText: { color: '#06663B', fontSize: 11, fontWeight: '700' }, body: { padding: 18 }, title: { fontSize: 25, fontWeight: '800', color: '#182230' }, subtitle: { fontSize: 14, lineHeight: 23, color: '#667085', marginTop: 7 }, metadata: { gap: 16, marginVertical: 25 }, row: { flexDirection: 'row', alignItems: 'center', gap: 14 }, value: { fontSize: 14, color: '#344054', flexShrink: 1 }, map: { marginLeft: 33, marginTop: -12, minHeight: 32, justifyContent: 'center' }, mapText: { color: '#0B7A3E', fontSize: 12, fontWeight: '700' }, description: { borderTopWidth: 1, borderTopColor: '#F0F1F3', paddingTop: 20, color: '#475467', fontSize: 14, lineHeight: 25 }, note: { fontSize: 11, lineHeight: 17, color: '#667085', marginTop: 18 }, confirmation: { flexDirection: 'row', gap: 8, alignItems: 'center', backgroundColor: '#ECF7EF', padding: 12, borderRadius: 10, marginTop: 18 }, confirmText: { color: '#076839', fontSize: 12, flex: 1 }, footer: { flexDirection: 'row', gap: 12, padding: 12, borderTopWidth: 1, borderTopColor: '#EAECF0' }, save: { flex: 1, minHeight: 50, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#DCE1E8', borderRadius: 12 }, saveText: { color: '#344054', fontWeight: '700' }, reminder: { flex: 1.5, minHeight: 50, flexDirection: 'row', gap: 8, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0B7A3E', borderRadius: 12 }, reminderText: { color: '#fff', fontWeight: '700', fontSize: 13 } });
