import React from 'react';
import { Image, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { DemoEvent, demoEvents } from './data/demoEvents';
export default function SavedEventsScreen({ saved, reminders, onSelect, onRemove, onExplore }: { saved: string[]; reminders: string[]; onSelect: (event: DemoEvent) => void; onRemove: (id: string) => void; onExplore: () => void }) {
 const events = demoEvents.filter(e => saved.includes(e.id));
 return <ScrollView showsVerticalScrollIndicator={false} showsHorizontalScrollIndicator={false} contentContainerStyle={s.content}><Text style={s.title}>Saved Events</Text><Text style={s.subtitle}>{events.length} saved {events.length === 1 ? 'experience' : 'experiences'} for your next adventure</Text>{events.map(event => <View key={event.id} style={s.card}><Pressable onPress={() => onSelect(event)} accessibilityLabel={'View ' + event.title}><Image source={event.image} style={s.image}/><View style={s.body}><Text style={s.name}>{event.title}</Text><Text style={s.meta}>{event.city} • {event.date}</Text><Text style={s.meta}>{event.venue}</Text><View style={s.bottom}><Text style={s.price}>{event.price ? 'LKR ' + event.price.toLocaleString() : 'Free'}</Text>{reminders.includes(event.id) && <Text style={s.price}>Reminder set</Text>}</View></View></Pressable><Pressable accessibilityLabel={'Unsave ' + event.title} onPress={() => onRemove(event.id)} style={s.heart}><Ionicons name="heart" size={24} color="#E44755"/></Pressable></View>)}{!events.length && <View style={s.empty}><Ionicons name="bookmark-outline" size={40} color="#0B7A3E"/><Text style={s.name}>Your next adventure starts here</Text><Text style={s.subtitle}>Save an event with its heart or Save button. It will appear here with its date and location.</Text><Pressable onPress={onExplore} style={s.button}><Text style={s.buttonText}>Explore Events</Text></Pressable></View>}<Text style={s.note}>Sample event details. Saved events stay on this device.</Text></ScrollView>;
}
const s = StyleSheet.create({ content: { padding: 18, width: '100%', maxWidth: 560, alignSelf: 'center' }, title: { fontSize: 26, fontWeight: '800', color: '#182230', marginBottom: 8 }, subtitle: { fontSize: 14, lineHeight: 21, color: '#667085', marginBottom: 22 }, card: { backgroundColor: '#fff', borderRadius: 16, borderWidth: 1, borderColor: '#EAECF0', overflow: 'hidden', marginBottom: 16 }, image: { width: '100%', height: 175 }, body: { padding: 15 }, name: { fontSize: 17, fontWeight: '700', color: '#182230' }, meta: { fontSize: 12, lineHeight: 20, color: '#667085', marginTop: 6 }, bottom: { flexDirection: 'row', justifyContent: 'space-between', marginTop: 12 }, price: { color: '#0B7A3E', fontSize: 12, fontWeight: '700' }, heart: { position: 'absolute', right: 12, top: 12, width: 44, height: 44, borderRadius: 22, backgroundColor: '#fff', alignItems: 'center', justifyContent: 'center' }, empty: { alignItems: 'center', gap: 15, paddingVertical: 50 }, button: { backgroundColor: '#0B7A3E', padding: 15, borderRadius: 12 }, buttonText: { color: '#fff', fontWeight: '700' }, note: { color: '#667085', fontSize: 11, textAlign: 'center', marginVertical: 14 } });
