import React, { useEffect, useState } from 'react';
import { ActivityIndicator, Image, RefreshControl, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { organizerEventService } from '../../services/api';
import { chats, Conversation } from '../../services/chats';
import { EventItem } from '../../types';
import { theme } from '../../constants/theme';
import { OrganizerBottomNav } from './components/OrganizerBottomNav';
import useStepBack from './useStepBack';
type Tab = 'Overview' | 'Attendees' | 'Messages';
export default function EventInsightsScreen({ navigation, route }: { navigation?: any; route?: any }) {
 const [events, setEvents] = useState<EventItem[]>([]), [selectedId, setSelectedId] = useState<string | null>(route?.params?.eventId ?? null);
 const [data, setData] = useState<any>(null), [threads, setThreads] = useState<Conversation[]>([]), [tab, setTab] = useState<Tab>('Overview');
 const [error, setError] = useState(''), [loading, setLoading] = useState(true), [insightsLoading, setInsightsLoading] = useState(false), [chatError, setChatError] = useState('');
 useStepBack(() => navigation?.navigate('OrganizerDashboard'));
 async function loadEvents() { setLoading(true); try { const rows = await organizerEventService.getEvents(); setEvents(rows); setSelectedId(current => rows.some(e => (e.id || e._id) === current) ? current : rows[0]?.id || rows[0]?._id || null); setError(''); } catch (err) { setError(err instanceof Error ? err.message : 'Could not load events.'); } finally { setLoading(false); } }
 async function loadChats() { try { setThreads(await chats.list()); setChatError(''); } catch (err) { setChatError(err instanceof Error ? err.message : 'Could not load messages.'); } }
 useEffect(() => { loadEvents(); loadChats(); }, []);
 useEffect(() => { let active = true; setData(null); if (!selectedId) return; setInsightsLoading(true); organizerEventService.getEventInsights(selectedId).then(result => { if (active) { setData(result); setError(''); } }).catch(err => { if (active) setError(err instanceof Error ? err.message : 'Could not load insights.'); }).finally(() => { if (active) setInsightsLoading(false); }); return () => { active = false; }; }, [selectedId]);
 useEffect(() => { if (!selectedId) return; let active = true; const timer = setInterval(() => { organizerEventService.getEventInsights(selectedId).then(result => { if (active) setData(result); }).catch(err => { if (active) setError(err.message); }); }, 10000); return () => { active = false; clearInterval(timer); }; }, [selectedId]);
 const event = data?.eventSummary ?? events.find(e => (e.id || e._id) === selectedId);
 const openChat = (chat: Conversation) => navigation?.navigate('Messages', { conversation: chat });
 const messages = <View style={s.section}><View style={s.sectionHeader}><Text style={s.sectionTitle}>Recent Messages / Inquiries</Text><TouchableOpacity onPress={() => navigation?.navigate('Messages')}><Text style={s.link}>See All</Text></TouchableOpacity></View><Text style={s.secondary}>Your organizer inbox across all events</Text>{chatError ? <TouchableOpacity onPress={loadChats}><Text accessibilityRole="alert" style={s.error}>{chatError} Tap to retry.</Text></TouchableOpacity> : threads.length ? threads.slice(0,3).map(chat => <TouchableOpacity key={chat.id} style={s.messageRow} onPress={() => openChat(chat)}><Ionicons name="person-circle-outline" size={38} color={theme.colors.primary}/><View style={{ flex: 1 }}><Text style={s.name}>{chat.other.fullName}</Text><Text numberOfLines={2} style={s.secondary}>{chat.lastMessage || 'Start a conversation'}</Text></View><Ionicons name="chevron-forward" size={18} color={theme.colors.muted}/></TouchableOpacity>) : <Text style={s.empty}>No inquiries yet. Messages from seekers will appear here.</Text>}</View>;
 return <View style={s.root}><View style={s.header}><TouchableOpacity accessibilityLabel="Back to dashboard" onPress={() => navigation?.navigate('OrganizerDashboard')} style={s.headerButton}><Ionicons name="chevron-back" size={24} color={theme.colors.text}/></TouchableOpacity><Text style={s.headerTitle}>Event Insights</Text><TouchableOpacity accessibilityLabel="Manage selected event" disabled={!selectedId} onPress={() => navigation?.navigate('ManageEvent', { eventId: selectedId })} style={s.headerButton}><Ionicons name="ellipsis-vertical" size={20} color={theme.colors.text}/></TouchableOpacity></View>
 <ScrollView contentContainerStyle={s.content} refreshControl={<RefreshControl refreshing={loading} onRefresh={() => { loadEvents(); loadChats(); if (selectedId) organizerEventService.getEventInsights(selectedId).then(setData).catch(err => setError(err.message)); }}/>}>{error ? <View><Text accessibilityRole="alert" style={s.error}>{error}</Text><TouchableOpacity onPress={loadEvents}><Text style={s.link}>Retry</Text></TouchableOpacity></View> : null}
 {loading ? <ActivityIndicator color={theme.colors.primary}/> : !events.length ? <View style={s.section}><Text style={s.sectionTitle}>No events yet</Text><Text style={s.empty}>Create an event to see its insights here.</Text><TouchableOpacity style={s.create} onPress={() => navigation?.navigate('CreateEventBasic')}><Text style={{ color: '#fff', fontWeight: '700' }}>Create New Event</Text></TouchableOpacity></View> : <>
 {events.length > 1 ? <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8 }}>{events.map(item => <TouchableOpacity key={item.id || item._id} onPress={() => setSelectedId(item.id || item._id!)} style={[s.eventChip, selectedId === (item.id || item._id) && { backgroundColor: '#DEF2E5' }]}><Text style={s.link}>{item.title}</Text></TouchableOpacity>)}</ScrollView> : null}
 {event ? <TouchableOpacity style={s.eventCard} onPress={() => navigation?.navigate('ManageEvent', { eventId: selectedId })}><Image source={event.images?.[0] ? { uri: event.images[0] } : require('../../../assets/logo.png')} style={s.image}/><View style={{ flex: 1 }}><Text style={s.name}>{event.title}</Text><Text style={s.secondary}>{event.startDate} · {event.city}</Text></View></TouchableOpacity> : null}
 <View style={s.tabs}>{(['Overview','Attendees','Messages'] as Tab[]).map(item => <TouchableOpacity key={item} accessibilityRole="tab" accessibilityState={{ selected: tab === item }} onPress={() => setTab(item)} style={[s.tab, tab === item && s.activeTab]}><Text style={[s.tabText, tab === item && { color: '#fff' }]}>{item}</Text></TouchableOpacity>)}</View>
 {insightsLoading ? <ActivityIndicator color={theme.colors.primary}/> : data ? <>{tab !== 'Messages' ? <View style={s.stats}>{([{ label: 'Views', value: data.viewsCount, icon: 'eye-outline', color: '#0B7A3E' }, { label: 'Interested', value: data.interestedCount, icon: 'heart', color: '#E4516B' }, { label: 'Going', value: data.goingCount, icon: 'people', color: '#3486E8' }] as const).map(stat => <View key={stat.label} style={s.stat}><Ionicons name={stat.icon} size={20} color={stat.color}/><Text style={s.statValue}>{Number(stat.value ?? 0).toLocaleString()}</Text><Text style={s.secondary}>{stat.label}</Text></View>)}</View> : null}
 {tab === 'Overview' ? <><View style={s.section}><Text style={s.sectionTitle}>Interest Over Time</Text><Text style={s.secondary}>Cumulative user actions</Text><View style={s.history}><Ionicons name="analytics-outline" size={32} color={theme.colors.muted}/><Text style={s.empty}>No activity history is available yet.</Text></View></View>{messages}</> : tab === 'Attendees' ? <View style={s.section}><Text style={s.sectionTitle}>Attendees</Text><Text style={s.empty}>No attendee list is available for this event.</Text></View> : messages}</> : null}
 </> }</ScrollView><OrganizerBottomNav activeTab="Events" onTabPress={next => { if (next === 'Home') navigation?.navigate('OrganizerDashboard'); if (next === 'Messages') navigation?.navigate('Messages'); if (next === 'Profile') navigation?.navigate('Profile'); }}/></View>;
}
const s = StyleSheet.create({ root: { flex: 1, backgroundColor: '#F6F8F7' }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#fff', padding: 8 }, headerButton: { width: 44, height: 44, alignItems: 'center', justifyContent: 'center' }, headerTitle: { fontSize: 18, fontWeight: '700', color: '#182230' }, content: { padding: 16, gap: 18, paddingBottom: 28 }, eventCard: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#fff', padding: 12, borderRadius: 14 }, image: { width: 60, height: 60, borderRadius: 10 }, name: { fontSize: 16, fontWeight: '700', color: '#182230' }, secondary: { fontSize: 13, color: '#667085', marginTop: 5, lineHeight: 19 }, eventChip: { padding: 12, borderRadius: 10, backgroundColor: '#fff' }, tabs: { flexDirection: 'row', backgroundColor: '#EAEEEC', borderRadius: 10, padding: 4 }, tab: { flex: 1, alignItems: 'center', paddingVertical: 10, borderRadius: 8 }, activeTab: { backgroundColor: '#0B7A3E' }, tabText: { fontSize: 13, fontWeight: '700', color: '#667085' }, stats: { flexDirection: 'row', gap: 10 }, stat: { flex: 1, alignItems: 'center', paddingVertical: 18, gap: 7, backgroundColor: '#fff', borderRadius: 14 }, statValue: { fontSize: 21, fontWeight: '700', color: '#182230' }, section: { padding: 16, backgroundColor: '#fff', borderRadius: 14 }, sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 }, sectionTitle: { fontSize: 16, fontWeight: '700', color: '#182230', flexShrink: 1 }, history: { minHeight: 180, alignItems: 'center', justifyContent: 'center' }, empty: { fontSize: 14, lineHeight: 22, color: '#667085', marginVertical: 16 }, link: { color: '#0B7A3E', fontWeight: '700', fontSize: 13 }, messageRow: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 14, borderBottomWidth: 1, borderBottomColor: '#EAECF0' }, error: { color: '#B42318', marginBottom: 10 }, create: { padding: 14, backgroundColor: '#0B7A3E', borderRadius: 10, alignItems: 'center' } });
